name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to upload artifacts to (Only needed for manual runs)'
        required: false
        default: ''

jobs:
  build:
    name: Publish Release artifacts
    runs-on: ubuntu-26.04
    permissions:
      contents: write # Ensures the GITHUB_TOKEN has permission to upload to releases

    steps:
      - name: Download artifacts from latest workflow
        uses: dawidd6/action-download-artifact@v20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          branch: ${{ github.event.release.target_commitish || 'main' }} # Fallback to main if run manually
          workflow_conclusion: success
          skip_unpack: false

      - name: Read package version
        run: |
          version="$(tr -d '\r\n' < tricore-gcc-artifacts/BASE-VER)"
          echo "PACKAGE_VERSION=$version" >> "$GITHUB_ENV"

      - name: Prepare linux package
        run: |
          mkdir linux-bundle && cd linux-bundle
          tar xf ../tricore-gcc-artifacts/gcc-linux.tar.gz
          tar xf ../tricore-qemu-linux-artifacts/qemu-linux.tar.gz
          tar xf ../tricore-gdb-linux-artifacts/gdb-linux.tar.gz
          tar -czf tricore-gcc-${{ env.PACKAGE_VERSION }}-linux.tar.gz ./*

      - name: Prepare windows package
        run: |
          mkdir win32-bundle && cd win32-bundle
          unzip ../tricore-gcc-artifacts/gcc-win32.zip
          unzip -o ../tricore-qemu-win32-artifacts/qemu-win32.zip
          unzip -o ../tricore-gdb-win32-artifacts/gdb-win32.zip
          zip -r9 tricore-gcc-${{ env.PACKAGE_VERSION }}-win32.zip ./*

      - name: Push release artifacts
        uses: softprops/action-gh-release@v2
        with:
          # Uses the release tag, the manual text input, or falls back to the package version
          tag_name: ${{ github.event.release.tag_name || github.event.inputs.tag_name || env.PACKAGE_VERSION }}
          files: |
            linux-bundle/*.tar.gz
            win32-bundle/*.zip
